# Config.yaml
model: Statisticals.Prophet # ex. NeuralNetworks.LSTM, NeuralNetworks.BiLSTM, etc.
data: ForexData/XAUUSD_H1
preprocess_parameters:
  filter_holidays: True
model_parameters:
  feature_columns: ["Open", "High", "Low", "Close", "Volume"]
  target_column: Volume
  seq_length: 24 # Length of input sequence
  train_ratio: 0.8 # 80% of data used for training
  epochs: 10 # Number of epochs for training
  batch_size: 32 # Batch size for training
stream_visualization:
  batch_size: 1 # Streaming one data point at a time
  update_interval: 50 # Initial streaming interval in ms
  max_points: 500 # Maximum number of points to display
  time_frame: "H" # Time frame to specify the width of candles
dashboard_visualization:
  n_cols: 3 # Number of column grid of loss charts
